version: "3"

services:
  server:
    container_name: "test-server"
    build: .
    volumes:
      - ./data:/home/data
    ports:
      - "8000:8000"
    command: python app/manage.py runserver --nostatic 0.0.0.0:8000
  execute_outgoing_transactions:
    container_name: "test-execute_outgoing_transactions"
    build: .
    volumes:
      - ./data:/home/data
    command: python app/manage.py execute_outgoing_transactions --loop
  watch_transaction:
    container_name: "test-watch_transactions"
    build: .
    volumes:
      - ./data:/home/data
    command: python app/manage.py watch_transactions
  process_pending_deposits:
    container_name: "test-process_pending_deposits"
    build: .
    volumes:
      - ./data:/home/data
    command: python app/manage.py process_pending_deposits --loop