version: "3"

services:
  db:
      image: postgres:14
      volumes:
        - ./data/db:/var/lib/postgresql/data
      environment:
        - POSTGRES_NAME=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
  server:
    container_name: "test-server"
    build: .
    volumes:
      - ./data:/home/data
    ports:
      - "8000:8000"
#    command: python app/manage.py runserver --nostatic 0.0.0.0:8000
    command: sh -c "python app/manage.py makemigrations &&
                    python app/manage.py migrate &&
                    python app/manage.py testnet issue --asset=TEST &&
                    python app/manage.py runserver --nostatic 0.0.0.0:8000"
    depends_on: # cannot start if db service is not up and running
      - db

  execute_outgoing_transactions:
    container_name: "test-execute_outgoing_transactions"
    build: .
    volumes:
      - ./data:/home/data
    command: python app/manage.py execute_outgoing_transactions --loop
    depends_on: # cannot start if db service is not up and running
      - db

  watch_transaction:
    container_name: "test-watch_transactions"
    build: .
    volumes:
      - ./data:/home/data
    command: python app/manage.py watch_transactions
    depends_on: # cannot start if db service is not up and running
      - db

  process_pending_deposits:
    container_name: "test-process_pending_deposits"
    build: .
    volumes:
      - ./data:/home/data
    command: python app/manage.py process_pending_deposits --loop
    depends_on: # cannot start if db service is not up and running
      - db