# Generated by Django 3.2.11 on 2022-02-01 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=56, unique=True)),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('additional_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerStellarAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stellar_account', models.CharField(max_length=56)),
                ('muxed_account', models.TextField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('memo_type', models.CharField(blank=True, choices=[('text', 'text'), ('id', 'id'), ('hash', 'hash')], max_length=4, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sep_12.customer')),
            ],
        ),
    ]
