# Generated by Django 3.2.12 on 2022-02-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sep_12', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_number',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
